var annotated_dup =
[
    [ "fmt", null, [
      [ "formatter< mxlFabricsProvider >", "structfmt_1_1formatter_3_01mxlFabricsProvider_01_4.html", "structfmt_1_1formatter_3_01mxlFabricsProvider_01_4" ],
      [ "formatter< ofi::Provider >", "structfmt_1_1formatter_3_01ofi_1_1Provider_01_4.html", "structfmt_1_1formatter_3_01ofi_1_1Provider_01_4" ]
    ] ],
    [ "mxl", "namespacemxl.html", [
      [ "lib", "namespacemxl_1_1lib.html", [
        [ "fabrics", "namespacemxl_1_1lib_1_1fabrics.html", [
          [ "ofi", "namespacemxl_1_1lib_1_1fabrics_1_1ofi.html", [
            [ "AddressVector", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1AddressVector.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1AddressVector" ],
            [ "AudioBounceBuffer", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1AudioBounceBuffer.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1AudioBounceBuffer" ],
            [ "AudioBounceBufferEntry", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1AudioBounceBufferEntry.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1AudioBounceBufferEntry" ],
            [ "AudioEntryHeader", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1AudioEntryHeader.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1AudioEntryHeader" ],
            [ "Completion", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Completion.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Completion" ],
            [ "CompletionQueue", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1CompletionQueue.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1CompletionQueue" ],
            [ "DataLayout", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1DataLayout.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1DataLayout" ],
            [ "Domain", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Domain.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Domain" ],
            [ "EfaAddress", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1EfaAddress.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1EfaAddress" ],
            [ "EgressProtocol", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1EgressProtocol.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1EgressProtocol" ],
            [ "EgressProtocolTemplate", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1EgressProtocolTemplate.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1EgressProtocolTemplate" ],
            [ "Endpoint", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Endpoint.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Endpoint" ],
            [ "Event", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Event.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Event" ],
            [ "EventQueue", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1EventQueue.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1EventQueue" ],
            [ "Exception", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Exception.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Exception" ],
            [ "Fabric", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Fabric.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Fabric" ],
            [ "FabricAddress", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricAddress.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricAddress" ],
            [ "FabricException", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricException.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricException" ],
            [ "FabricInfo", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInfo.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInfo" ],
            [ "FabricInfoIterator", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInfoIterator.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInfoIterator" ],
            [ "FabricInfoList", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInfoList.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInfoList" ],
            [ "FabricInfoView", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInfoView.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInfoView" ],
            [ "FabricInterfaceDescription", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInterfaceDescription.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInterfaceDescription" ],
            [ "FabricInterfaceList", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInterfaceList.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricInterfaceList" ],
            [ "FabricsInstance", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricsInstance.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1FabricsInstance" ],
            [ "ImmDataGrain", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1ImmDataGrain.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1ImmDataGrain" ],
            [ "IngressProtocol", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1IngressProtocol.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1IngressProtocol" ],
            [ "Initiator", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Initiator.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Initiator" ],
            [ "InitiatorWrapper", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1InitiatorWrapper.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1InitiatorWrapper" ],
            [ "LocalRegion", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1LocalRegion.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1LocalRegion" ],
            [ "LocalRegionGroup", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1LocalRegionGroup.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1LocalRegionGroup" ],
            [ "LocalRegionGroupSpan", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1LocalRegionGroupSpan.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1LocalRegionGroupSpan" ],
            [ "MemoryRegion", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1MemoryRegion.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1MemoryRegion" ],
            [ "MxlRegions", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1MxlRegions.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1MxlRegions" ],
            [ "OfiSockaddrIb", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1OfiSockaddrIb.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1OfiSockaddrIb" ],
            [ "overloaded", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1overloaded.html", null ],
            [ "PassiveEndpoint", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1PassiveEndpoint.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1PassiveEndpoint" ],
            [ "ProviderCapabilities", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1ProviderCapabilities.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1ProviderCapabilities" ],
            [ "ProviderConfig", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1ProviderConfig.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1ProviderConfig" ],
            [ "ProviderConfigValues", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1ProviderConfigValues.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1ProviderConfigValues" ],
            [ "RawFabricAddress", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RawFabricAddress.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RawFabricAddress" ],
            [ "RCInitiator", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RCInitiator.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RCInitiator" ],
            [ "RCInitiatorEndpoint", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RCInitiatorEndpoint.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RCInitiatorEndpoint" ],
            [ "RCTarget", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RCTarget.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RCTarget" ],
            [ "RDMInitiator", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RDMInitiator.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RDMInitiator" ],
            [ "RDMInitiatorTarget", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RDMInitiatorTarget.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RDMInitiatorTarget" ],
            [ "RDMTarget", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RDMTarget.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RDMTarget" ],
            [ "Region", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Region.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Region" ],
            [ "RegionGroup", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RegionGroup.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RegionGroup" ],
            [ "RegisteredRegion", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RegisteredRegion.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RegisteredRegion" ],
            [ "RemoteRegion", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1RemoteRegion.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1RemoteRegion" ],
            [ "RemoteRegionGroup", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RemoteRegionGroup.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RemoteRegionGroup" ],
            [ "RMAGrainEgressProtocol", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMAGrainEgressProtocol.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMAGrainEgressProtocol" ],
            [ "RMAGrainEgressProtocolTemplate", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMAGrainEgressProtocolTemplate.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMAGrainEgressProtocolTemplate" ],
            [ "RMAGrainIngressProtocol", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMAGrainIngressProtocol.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMAGrainIngressProtocol" ],
            [ "RMASampleEgressProtocol", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMASampleEgressProtocol.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMASampleEgressProtocol" ],
            [ "RMASampleEgressProtocolTemplate", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMASampleEgressProtocolTemplate.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMASampleEgressProtocolTemplate" ],
            [ "RMASampleIngressProtocol", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMASampleIngressProtocol.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1RMASampleIngressProtocol" ],
            [ "SliceRange", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1SliceRange.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1SliceRange" ],
            [ "Target", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Target.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1Target" ],
            [ "TargetInfo", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1TargetInfo.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1TargetInfo" ],
            [ "TargetInfoBounceBufferInfo", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1TargetInfoBounceBufferInfo.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1TargetInfoBounceBufferInfo" ],
            [ "TargetSetupOptions", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1TargetSetupOptions.html", "structmxl_1_1lib_1_1fabrics_1_1ofi_1_1TargetSetupOptions" ],
            [ "TargetWrapper", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1TargetWrapper.html", "classmxl_1_1lib_1_1fabrics_1_1ofi_1_1TargetWrapper" ]
          ] ]
        ] ],
        [ "ContinuousFlowData", "classmxl_1_1lib_1_1ContinuousFlowData.html", "classmxl_1_1lib_1_1ContinuousFlowData" ],
        [ "ContinuousFlowReader", "classmxl_1_1lib_1_1ContinuousFlowReader.html", "classmxl_1_1lib_1_1ContinuousFlowReader" ],
        [ "ContinuousFlowWriter", "classmxl_1_1lib_1_1ContinuousFlowWriter.html", "classmxl_1_1lib_1_1ContinuousFlowWriter" ],
        [ "Deferred", "classmxl_1_1lib_1_1Deferred.html", "classmxl_1_1lib_1_1Deferred" ],
        [ "DiscreteFlowData", "classmxl_1_1lib_1_1DiscreteFlowData.html", "classmxl_1_1lib_1_1DiscreteFlowData" ],
        [ "DiscreteFlowReader", "classmxl_1_1lib_1_1DiscreteFlowReader.html", "classmxl_1_1lib_1_1DiscreteFlowReader" ],
        [ "DiscreteFlowWriter", "classmxl_1_1lib_1_1DiscreteFlowWriter.html", "classmxl_1_1lib_1_1DiscreteFlowWriter" ],
        [ "DomainWatcher", "classmxl_1_1lib_1_1DomainWatcher.html", "classmxl_1_1lib_1_1DomainWatcher" ],
        [ "DomainWatcherRecord", "structmxl_1_1lib_1_1DomainWatcherRecord.html", "structmxl_1_1lib_1_1DomainWatcherRecord" ],
        [ "Duration", "structmxl_1_1lib_1_1Duration.html", "structmxl_1_1lib_1_1Duration" ],
        [ "Flow", "structmxl_1_1lib_1_1Flow.html", "structmxl_1_1lib_1_1Flow" ],
        [ "FlowData", "classmxl_1_1lib_1_1FlowData.html", "classmxl_1_1lib_1_1FlowData" ],
        [ "FlowIoFactory", "classmxl_1_1lib_1_1FlowIoFactory.html", "classmxl_1_1lib_1_1FlowIoFactory" ],
        [ "FlowManager", "classmxl_1_1lib_1_1FlowManager.html", "classmxl_1_1lib_1_1FlowManager" ],
        [ "FlowOptionsParser", "classmxl_1_1lib_1_1FlowOptionsParser.html", "classmxl_1_1lib_1_1FlowOptionsParser" ],
        [ "FlowParser", "classmxl_1_1lib_1_1FlowParser.html", "classmxl_1_1lib_1_1FlowParser" ],
        [ "FlowReader", "classmxl_1_1lib_1_1FlowReader.html", "classmxl_1_1lib_1_1FlowReader" ],
        [ "FlowReaderFactory", "classmxl_1_1lib_1_1FlowReaderFactory.html", "classmxl_1_1lib_1_1FlowReaderFactory" ],
        [ "FlowState", "structmxl_1_1lib_1_1FlowState.html", "structmxl_1_1lib_1_1FlowState" ],
        [ "FlowSynchronizationGroup", "classmxl_1_1lib_1_1FlowSynchronizationGroup.html", "classmxl_1_1lib_1_1FlowSynchronizationGroup" ],
        [ "FlowWriter", "classmxl_1_1lib_1_1FlowWriter.html", "classmxl_1_1lib_1_1FlowWriter" ],
        [ "FlowWriterFactory", "classmxl_1_1lib_1_1FlowWriterFactory.html", "classmxl_1_1lib_1_1FlowWriterFactory" ],
        [ "Grain", "structmxl_1_1lib_1_1Grain.html", "structmxl_1_1lib_1_1Grain" ],
        [ "GrainHeader", "structmxl_1_1lib_1_1GrainHeader.html", "structmxl_1_1lib_1_1GrainHeader" ],
        [ "Instance", "classmxl_1_1lib_1_1Instance.html", "classmxl_1_1lib_1_1Instance" ],
        [ "PosixContinuousFlowReader", "classmxl_1_1lib_1_1PosixContinuousFlowReader.html", "classmxl_1_1lib_1_1PosixContinuousFlowReader" ],
        [ "PosixContinuousFlowWriter", "classmxl_1_1lib_1_1PosixContinuousFlowWriter.html", "classmxl_1_1lib_1_1PosixContinuousFlowWriter" ],
        [ "PosixDiscreteFlowReader", "classmxl_1_1lib_1_1PosixDiscreteFlowReader.html", "classmxl_1_1lib_1_1PosixDiscreteFlowReader" ],
        [ "PosixDiscreteFlowWriter", "classmxl_1_1lib_1_1PosixDiscreteFlowWriter.html", "classmxl_1_1lib_1_1PosixDiscreteFlowWriter" ],
        [ "PosixFlowIoFactory", "structmxl_1_1lib_1_1PosixFlowIoFactory.html", "structmxl_1_1lib_1_1PosixFlowIoFactory" ],
        [ "SharedMemoryBase", "classmxl_1_1lib_1_1SharedMemoryBase.html", "classmxl_1_1lib_1_1SharedMemoryBase" ],
        [ "SharedMemoryInstance", "structmxl_1_1lib_1_1SharedMemoryInstance.html", "structmxl_1_1lib_1_1SharedMemoryInstance" ],
        [ "SharedMemorySegment", "structmxl_1_1lib_1_1SharedMemorySegment.html", "structmxl_1_1lib_1_1SharedMemorySegment" ],
        [ "Timepoint", "structmxl_1_1lib_1_1Timepoint.html", "structmxl_1_1lib_1_1Timepoint" ]
      ] ],
      [ "tests", "namespacemxl_1_1tests.html", [
        [ "mxlDomainFixture", "classmxl_1_1tests_1_1mxlDomainFixture.html", "classmxl_1_1tests_1_1mxlDomainFixture" ]
      ] ]
    ] ],
    [ "BatchIndexAndSize", "structBatchIndexAndSize.html", "structBatchIndexAndSize" ],
    [ "MockFlowFiles", "structMockFlowFiles.html", "structMockFlowFiles" ],
    [ "MockWriter", "structMockWriter.html", "structMockWriter" ],
    [ "mxlBufferSlice_t", "structmxlBufferSlice__t.html", "structmxlBufferSlice__t" ],
    [ "mxlCommonFlowConfigInfo_t", "structmxlCommonFlowConfigInfo__t.html", "structmxlCommonFlowConfigInfo__t" ],
    [ "mxlContinuousFlowConfigInfo_t", "structmxlContinuousFlowConfigInfo__t.html", "structmxlContinuousFlowConfigInfo__t" ],
    [ "mxlDiscreteFlowConfigInfo_t", "structmxlDiscreteFlowConfigInfo__t.html", "structmxlDiscreteFlowConfigInfo__t" ],
    [ "mxlFabricsEndpointAddress_t", "structmxlFabricsEndpointAddress__t.html", "structmxlFabricsEndpointAddress__t" ],
    [ "mxlFabricsInitiatorConfig_t", "structmxlFabricsInitiatorConfig__t.html", "structmxlFabricsInitiatorConfig__t" ],
    [ "mxlFabricsInterfaceCaps_t", "structmxlFabricsInterfaceCaps__t.html", "structmxlFabricsInterfaceCaps__t" ],
    [ "mxlFabricsInterfaceConfig_t", "structmxlFabricsInterfaceConfig__t.html", "structmxlFabricsInterfaceConfig__t" ],
    [ "mxlFabricsInterfaceList_t", "structmxlFabricsInterfaceList__t.html", "structmxlFabricsInterfaceList__t" ],
    [ "mxlFabricsTargetConfig_t", "structmxlFabricsTargetConfig__t.html", "structmxlFabricsTargetConfig__t" ],
    [ "mxlFlowConfigInfo_t", "structmxlFlowConfigInfo__t.html", "structmxlFlowConfigInfo__t" ],
    [ "mxlFlowInfo_t", "structmxlFlowInfo__t.html", "structmxlFlowInfo__t" ],
    [ "mxlFlowRuntimeInfo_t", "structmxlFlowRuntimeInfo__t.html", "structmxlFlowRuntimeInfo__t" ],
    [ "mxlGrainInfo_t", "structmxlGrainInfo__t.html", "structmxlGrainInfo__t" ],
    [ "mxlMutableBufferSlice_t", "structmxlMutableBufferSlice__t.html", "structmxlMutableBufferSlice__t" ],
    [ "mxlMutableWrappedBufferSlice_t", "structmxlMutableWrappedBufferSlice__t.html", "structmxlMutableWrappedBufferSlice__t" ],
    [ "mxlMutableWrappedMultiBufferSlice_t", "structmxlMutableWrappedMultiBufferSlice__t.html", "structmxlMutableWrappedMultiBufferSlice__t" ],
    [ "mxlRational_t", "structmxlRational__t.html", "structmxlRational__t" ],
    [ "mxlVersionType", "structmxlVersionType.html", "structmxlVersionType" ],
    [ "mxlWrappedBufferSlice_t", "structmxlWrappedBufferSlice__t.html", "structmxlWrappedBufferSlice__t" ],
    [ "mxlWrappedMultiBufferSlice_t", "structmxlWrappedMultiBufferSlice__t.html", "structmxlWrappedMultiBufferSlice__t" ]
];